W4D4-master/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :index, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :index, :show, :update, :destroy] 

  resources :notes, only: [:create, :destroy]

end

W4D4-master/app/models/note.rb
class Note < ApplicationRecord
  validates :body, presence: true

  belongs_to :user,
    foreign_key: :user_id,
    class_name: :User

  belongs_to :track,
    foreign_key: :track_id,
    class_name: :Track
end

W4D4-master/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :ensure_logged_in

  def create
    note = Note.new(note_params)
    note.user_id = current_user.id
    if note.save

    else
      flash[:errors] = note.errors.full_messages
    end
    redirect_to track_url(note.track_id)
  end

  def destroy
    note = Note.find(params[:id])
    if note && current_user.id == note.user_id
      track_id = note.track_id
      note.destroy
      redirect_to track_url(track_id)
    elsif note
      track_id = note.track_id
      redirect_to track_url(track_id), status: 403
    else
      redirect_to bands_url
    end
  end

  private

  def note_params
    params.require(:note).permit(:track_id, :body)
  end
end

W4D4-master/app/views/notes/_form.html.erb
<% note ||= Note.new %>

<form action="<%= notes_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="note[track_id]" value="<%= track_id %>">
  <textarea name="note[body]" rows="8" cols="80"><%= note.body %></textarea>
  <br/>
  <input type="submit" name="" value="Make Note">
</form>

W4D4-master/app/views/notes/_note.html.erb
<div class="notes">
  <%= note.body %>
  <br/>
  By: <%= note.user.email %>
  <br/>
  <% if current_user.id == note.user_id %>
    <form action="<%= note_url(note) %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" name="" value="DELETE NOTE">
    </form>
  <% end %>
</div>