W4D4-master/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :index, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :index, :show, :update, :destroy] 

  resources :notes, only: [:create, :destroy]

end

W4D4-master/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :bigint(8)        not null, primary key
#  album_id   :integer          not null
#  title      :string           not null
#  ord        :integer
#  lyrics     :text
#  is_bonus   :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  validates :title, presence: true

  after_initialize :ensure_is_bonus

  def ensure_is_bonus
    self.is_bonus = false if self.is_bonus.nil?
  end

  belongs_to :album,
    foreign_key: :album_id,
    class_name: :Album

  has_one :band,
    through: :album,
    source: :band

  has_many :notes,
    foreign_key: :track_id,
    class_name: :Note,
    dependent: :destroy

  def sibling_tracks
    album.tracks.where.not(id: self.id)
  end

end

W4D4-master/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :ensure_logged_in

  def index
    @tracks = Track.all
    render :index
  end

  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    @track.is_bonus = bonus_or_regular?(track_params[:is_bonus])
    if @track.save
      redirect_to track_url(@track.id)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to new_album_track_url(album_id: @track.album_id)
    end
  end

  def show
    @track = Track.find_by(id: params[:id])
    if @track
      render :show
    else
      redirect_to tracks_url
    end
  end

  def edit
    @track = Track.find_by(id: params[:id])
    render :edit
  end

  def update
    track = Track.find_by(id: params[:id])
    if !track
      redirect_to tracks_url
    elsif track.update(track_params)
      track.update(is_bonus: bonus_or_regular?(track_params[:is_bonus]))
      redirect_to track_url(track.id)
    else
      flash[:errors] = track.errors.full_messages
      redirect_to edit_track_url(track.id)
    end
  end

  def destroy
    track = Track.find_by(id: params[:id])
    album_id = track.album_id
    track.destroy
    redirect_to album_url(album_id)
  end

  private

  def track_params
    params.require(:track).permit(:album_id, :title, :ord, :lyrics, :is_bonus)
  end

  def bonus_or_regular?(is_bonus)
    is_bonus == 'bonus'
  end

end

W4D4-master/app/views/tracks/_track.html.erb
<div class="tracks">
  <a href="<%= track_url(track.id) %>"><%= track.title %></a>
</div>

W4D4-master/app/views/tracks/edit.html.erb
<h3>Edit Track Info</h3>

<%= render 'shared/track_form', url: track_url(@track.id), method: 'patch', action: 'EDIT TRACK', track: @track%>

W4D4-master/app/views/tracks/index.html.erb
<h2>Tracks</h2>

<section id='tracks-index'>
  <%= render @tracks %>
</section>

W4D4-master/app/views/tracks/new.html.erb
<h3>Enter New Track Info</h3>

<%= render 'shared/track_form', url: tracks_url, method: 'post', action: 'ENTER TRACK', track: @track%>

W4D4-master/app/views/tracks/show.html.erb
<section class='show-info'>
  <h2>Song: <%= @track.title.upcase %></h2>

  <section class='info-list'>
    <h4>Band:</h4>
    <p><%= @track.band.name %></p>

    <h4>Album:</h4>
    <p><%= @track.album.title %></p>

    <h4>Track Number:</h4>
    <p><%= @track.ord %></p>

    <%= "#{@track.is_bonus ? 'Bonus' : 'Regular'} Track"%>
    <div id='lyrics-heading'>Lyrics:</div>
  </section>
  <pre id='show-lyrics'><%= h(ugly_lyrics(@track.lyrics)) %></pre>
</section>

<section class= 'show-links'>
<%= button(edit_track_url(@track.id), 'EDIT TRACK') %>
<br/>
<%= button(band_url(@track.band.id), 'GO TO BAND') %>
<br/>
<%= button(album_url(@track.album_id), 'GO TO ALBUM') %>
<form action="<%= track_url(@track.id) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="DELETE TRACK">
</form>
</section>
<section class='show-children'>
<h3>Notes</h3>
<h5>Make a new note</h5>
<%= render 'notes/form', track_id: @track.id %>
<br/>
<br/>
<%= render @track.notes %>
</section>