W4D4-master/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :index, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :index, :show, :update, :destroy] 

  resources :notes, only: [:create, :destroy]

end

W4D4-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <h1>MusicApp</h1>
        <div class="sign-up">
          <% if current_user %>
            <form action="<%= session_url %>" method="post">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              <input type="hidden" name="_method" value="delete">
              <input type="submit" value="LOG OUT" class='nav-buttons log-out'>
            </form>
          <% else %>
            <%= button(new_user_url, 'SIGN UP') %>
            <%= button(new_session_url, 'LOG IN') %>
          <% end %>
        </div>
      </nav>
    </header>

    <main>
      <% if flash[:errors] %>
        <ul>
          <% flash[:errors].each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>