W4D4-master/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :index, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :index, :show, :update, :destroy] 

  resources :notes, only: [:create, :destroy]

end

W4D4-master/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  year       :integer
#  is_live    :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, presence: true

  after_initialize :ensure_is_live

  def ensure_is_live
    self.is_live = false if self.is_live.nil?
  end

  belongs_to :band,
    foreign_key: :band_id,
    class_name: :Band

  has_many :tracks,
    foreign_key: :album_id,
    class_name: :Track,
    dependent: :destroy
end

W4D4-master/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :ensure_logged_in

  def index
    @albums = Album.all
    render :index
  end

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    @album.is_live = live_or_studio?(params[:album][:is_live])
    if @album.save
      redirect_to album_url(@album.id)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to new_band_album_url(band_id: @album.band_id)
    end
  end

  def show
    @album = Album.find_by(id: params[:id])
    if @album
      render :show
    else
      redirect_to albums_url
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def update
    album = Album.find_by(id: params[:id])
    if !album
      redirect_to albums_url
    elsif album.update(album_params)
      album.update(is_live: live_or_studio?(params[:album][:is_live]))
      redirect_to album_url(album.id)
    else
      flash[:errors] = album.errors.full_messages
      redirect_to edit_album_url(album.id)
    end
  end

  def destroy
    album = Album.find_by(id: params[:id])
    band_id = album.band_id
    album.destroy
    redirect_to band_url(band_id)
  end

  def live_or_studio?(is_live)
    is_live == 'live'
  end

  private

  def album_params
    params.require(:album).permit(:band_id, :title, :year, :is_live)
  end

end

W4D4-master/app/views/albums/_album.html.erb
<div class="albums">
  <a href="<%= album_url(album.id) %>"><%= album.title %></a>
</div>

W4D4-master/app/views/albums/edit.html.erb
<h3>Edit Album Info</h3>

<%= render 'shared/album_form', url: album_url(@album.id), method: 'patch', action: 'EDIT ALBUM', album: @album%>

W4D4-master/app/views/albums/index.html.erb
<h2>Albums</h2>

<section id='albums-index'>
  <%= render @albums %>
</section>

W4D4-master/app/views/albums/new.html.erb
<h3>Enter New Album Info</h3>

<%= render 'shared/album_form', url: albums_url, method: 'post', action: 'ENTER ALBUM', album: @album%>

W4D4-master/app/views/albums/show.html.erb
<section class='show-info'>
<h2>Album: <%= @album.title.upcase %></h2>

By: <%= @album.band.name %>
<br/>
Year: <%= @album.year %>
<br/>
<%= "#{@album.is_live ? 'Live' : 'Studio'} Album"%>
</section>

<section class='show-children'>
  <h3>Tracks</h3>
  <%= render @album.tracks %>
</section>

<section class= 'show-links'>
<%= button(new_album_track_url(@album.id), 'NEW TRACK') %>
<br/>
<%= button(band_url(@album.band_id), 'GO TO BAND') %>
<br/>
<%= button(edit_album_url(@album.id), 'EDIT ALBUM') %>
<form action="<%= album_url(@album.id) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="DELETE ALBUM">
</form>
</section>